name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23.2"
                  cache: true

            - name: Install dependencies
              run: make deps

            - name: Format check
              run: make fmt

            - name: Lint
              run: make lint

            - name: Test
              run: make test
