services:
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: ${IMAGE:-garethcxy/homekit-cli-dev}:${TAG:-latest}
    volumes:
      - ..:/work
      - ~/.gitconfig:/home/dev/.gitconfig:ro
    working_dir: /work/homekit-cli
    tty: true
    stdin_open: true
